apiVersion: v1
kind: Service
metadata: 
  name: hello
spec: 
  selector:
    app: hello
    tier: backend
    track: stable
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
