apiVersion: v1
kind: Service
metadata: 
  name: frontend
spec:
  selector:
    app: hello
    tier: frontend
    track: stable
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
